addSbtPlugin("io.get-coursier"  % "sbt-coursier"         % "1.0.0")
addSbtPlugin("com.geirsson"     % "sbt-scalafmt"         % "1.4.0")
addSbtPlugin("com.timushev.sbt" % "sbt-updates"          % "0.3.2")
addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.9.0")
addSbtPlugin("org.wartremover"  % "sbt-wartremover"      % "2.2.1")
addSbtPlugin("io.spray" % "sbt-revolver" % "0.9.1")